### ISSUE TITLE
根据步骤进行，日志显示错误，请问哪里错误了，谢谢！

### ISSUE THREAD

**Issue by ZaichunLi** [ICE99125/weibo_checkin#14]
![image](https://user-images.githubusercontent.com/110941152/183768321-c909e98a-9bb5-45fd-b866-57bda6f78a57.png)

**Comment by ICE99125** [comment]
改入口为 main 哦，默认是 main_handler

**Comment by ZaichunLi** [comment]
请问一下这是什么原因呀，谢谢！
![image](https://user-images.githubusercontent.com/110941152/183823482-04910c1c-74ec-453b-890d-086a1ecae207.png)

**Comment by ICE99125** [comment]
cookie 获取的不对吧

**Comment by ICE99125** [comment]
你抓包的信息对了吗

**Comment by ZaichunLi** [comment]
我再试一下，谢谢！

**Comment by ZaichunLi** [comment]
![image](https://user-images.githubusercontent.com/110941152/183829557-df5aaf18-98e6-40f4-8223-52db7c18c668.png)
代码中的uid指的是抓包中的aid吗

**Comment by ZaichunLi** [comment]
重新抓包之后还是这样，请问一下怎么解决，谢谢！
![image](https://user-images.githubusercontent.com/110941152/183829821-fa9133d9-99f0-4790-b5f0-82eb513e6827.png)

**Comment by ICE99125** [comment]
![image](https://user-images.githubusercontent.com/65435402/183831797-e2a7ee61-c473-4ce4-9edb-361b7dffba83.png)
uid 是用户 id， 应该会有的呀，你的信息怎么那么少呀

**Comment by ZaichunLi** [comment]
![image](https://user-images.githubusercontent.com/110941152/183833196-7520d812-c212-43bc-b819-2c0012a64b9f.png)
你的微博国际版是什么版本呀

**Comment by ICE99125** [comment]
我没用国际版呀，就是普通的国内版本

**Comment by ZaichunLi** [comment]
谢谢大佬，已成功。之前看了很多攻略都是用国际版抓包，刚换成普通版抓包之后数据正常能运行了，谢谢谢谢！
