### ISSUE TITLE
请问怎么开启推送呢？

### ISSUE THREAD

**Issue by jiuchu** [ICE99125/weibo_checkin#16]
运行成功了，但是没用推送，环境变量是腾讯云的环境变量吗？key值是plus？还是plusplus呢。。

**Comment by ICE99125** [comment]
pushplus

**Comment by ICE99125** [comment]
主要是写了几个云函数，这个说明就懒得写那么详细了😂

**Comment by jiuchu** [comment]
> 主要是写了几个云函数，这个说明就懒得写那么详细了😂

未开启推送  腾讯云环境变量配置了pushplus 还是提示未开启推送 是不是配置文件里面还要改什么啊？

**Comment by ICE99125** [comment]
需要把 push 的注释取消掉,写上要推送的类型

**Comment by jiuchu** [comment]
> 需要把 push 的注释取消掉,写上要推送的类型
共获取到59个超话  我只关注了59个超话 怎么就发送内容过大了、。。
我把最下面的 "push": "pushplus", # 推送类型, together 为 True 或者不写时必须有, 否则不推送这条放开了 就改了这个16行

 http://www.pushplus.plus:80 "POST /send HTTP/1.1" 200 None

发送消息失败, 因为: 发送内容过大，不能超过2万字

Response RequestId: a3fa8f21-42d1-458f-8d5d-1a16799cc05c RetMsg: null

END RequestId: a3fa8f21-42d1-458f-8d5d-1a16799cc05c

Report RequestId: a3fa8f21-42d1-458f-8d5d-1a16799cc05c Duration: 745510ms Memory: 128MB MemUsage: 16.52MB

**Comment by ICE99125** [comment]
pushplus推送消息有字数限制, 只能改别的推送了

**Comment by ICE99125** [comment]
你是多个账号嘛,按理说2万字59个不应该超了

**Comment by jiuchu** [comment]
> 你是多个账号嘛,按理说2万字59个不应该超了

我就一个！改别的推送咋改呢。。

**Comment by ICE99125** [comment]
workWechat qmsg workWechatRobot server pushplus

**Comment by ICE99125** [comment]
比如改 server 酱

**Comment by jiuchu** [comment]
> 比如改 server 酱

"push": "server 酱", 是这样嘛  环境变量的key值是什么呢

**Comment by ICE99125** [comment]
"push": "server"

**Comment by jiuchu** [comment]
> "push": "server"

配置里改了 未配置 server 酱 的 key    腾讯云环境变量key是push还是server还是啥。。

**Comment by ICE99125** [comment]
环境变量是 server, 什么推送就是什么 key

**Comment by jiuchu** [comment]
> 环境变量是 server, 什么推送就是什么 key

弄好了感谢 就是

排名 | 经验 | 积分 | 连续天数 这些数据怎么是空的呢

**Comment by ICE99125** [comment]
只有第一次签到有数据
