### ISSUE TITLE
为什么有时候推送结果是fun_data

### ISSUE THREAD

**Issue by jiuchu** [ICE99125/weibo_checkin#17]
不过签到是成功的，还有积分这个为啥一直都是0，没有值吗。

**Comment by ICE99125** [comment]
这个积分是微博返回的，什么时候有值我也不知道，其实也没啥用吧，至于 fun_data 有图吗

**Comment by jiuchu** [comment]
> 这个积分是微博返回的，什么时候有值我也不知道，其实也没啥用吧，至于 fun_data 有图吗
![微信截图_20220826133500](https://user-images.githubusercontent.com/57851230/186829824-efd25d95-3cd2-445e-a33e-725694d26d7b.png)

**Comment by jiuchu** [comment]
> 这个积分是微博返回的，什么时候有值我也不知道，其实也没啥用吧，至于 fun_data 有图吗

图发了大佬

**Comment by ICE99125** [comment]
你在weibo.py的209行写一个print(e)看看打印了什么
