### ISSUE TITLE
可以获取并成功签到，但是提示错误

### ISSUE THREAD

**Issue by zhheo** [ICE99125/weibo_checkin#4]
![image](https://user-images.githubusercontent.com/33177975/131114577-b59edb52-4aa3-4aa5-8bb3-73561c4deab1.png)
以下是错误信息：
{"errorCode":-1,"errorMessage":"Invoking task timed out after 3 seconds","requestId":"04ae2f14-6e16-4763-93db-5b192b84de99","statusCode":433}

**Comment by ICE99125** [comment]
需要将执行超时时间设置长一点，默认3s

**Comment by zhheo** [comment]
非常感谢！
